//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITSupport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public long IDCourse { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Saleprice { get; set; }
        public string Describe { get; set; }
        public string Images { get; set; }
        public Nullable<int> IDCreator { get; set; }
        public Nullable<int> IDToppic { get; set; }
        public Nullable<int> IDPH { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual ACourse ACourse { get; set; }
        public virtual PublishingHouse PublishingHouse { get; set; }
        public virtual Topic Topic { get; set; }
    }
}
