//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITSupport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseQuestion
    {
        public long CourseId { get; set; }
        public long QuestionId { get; set; }
        public Nullable<int> Order { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Question Question { get; set; }
    }
}
