//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITSupport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionAnswer
    {
        public long Id { get; set; }
        public long SessionId { get; set; }
        public long QuestionId { get; set; }
        public long AnswerId { get; set; }
        public bool IsCorrect { get; set; }
        public Nullable<System.DateTimeOffset> CreatedAt { get; set; }
    
        public virtual Answer Answer { get; set; }
        public virtual Question Question { get; set; }
        public virtual TestSession TestSession { get; set; }
    }
}
