//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITSupport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestSession
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TestSession()
        {
            this.SessionAnswer = new HashSet<SessionAnswer>();
        }
    
        public long Id { get; set; }
        public long CourseId { get; set; }
        public long UserId { get; set; }
        public System.DateTimeOffset StartTime { get; set; }
        public Nullable<System.DateTimeOffset> EndTime { get; set; }
        public int Total { get; set; }
        public int Correct { get; set; }
    
        public virtual Course Course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SessionAnswer> SessionAnswer { get; set; }
        public virtual User User { get; set; }
    }
}
